version: '2'
services:
    heartmonitor-app:
        image: heartmonitor
        external_links:
            - heartmonitor-postgresql:postgresql
            - heartmonitor-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/heartMonitor
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    heartmonitor-postgresql:
        extends:
            file: postgresql.yml
            service: heartmonitor-postgresql
    heartmonitor-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: heartmonitor-elasticsearch
